
FILE:	tests/parser/keywords/keywords.js
TOKENS:	0:0 Variable (Const)
	0:0 Variable (Let)
	0:0 Variable (Var)
	0:0 Enum
	0:0 Import
	0:0 Class
	0:0 With
	0:0 While
	0:0 Void
	0:0 Typeof
	0:0 Try
	0:0 Throw
	0:0 This
	0:0 Super
	0:0 Return
	0:0 Null
	0:0 New
	0:0 Instanceof
	0:0 In
	0:0 If
	0:0 Function
	0:0 For
	0:0 Finally
	0:0 Extends
	0:0 Exports
	0:0 Else
	0:0 Do
	0:0 Default
	0:0 Delete
	0:0 Debugger
	0:0 Continue
	0:0 Catch
	0:0 Case
	0:0 Break
