FILE:	/Users/nick/projects/infrared/tests/lexer/array/array.js
TOKENS:
  Array [] [90m(1:1)[39m
  Array [] [90m(2:1)[39m
  Array [
      Array [] [90m(3:2)[39m
  ] [90m(3:1)[39m
  Array [
      Array [] [90m(4:2)[39m
  ] [90m(4:1)[39m
  Array [
      Array [
          Array [] [90m(5:3)[39m
      ] [90m(5:2)[39m
  ] [90m(5:1)[39m
  Array [
      Array [
          Array [] [90m(6:3)[39m
      ] [90m(6:2)[39m
  ] [90m(6:1)[39m
  Array [
      Array [] [90m(7:2)[39m
      Array [] [90m(7:4)[39m
  ] [90m(7:1)[39m
  Array [
      Array [
          Array [] [90m(8:2)[39m
          Array [] [90m(8:5)[39m
      ] [90m(8:4)[39m
  ] [90m(8:1)[39m
  Array [
      Identifier: a [90m(10:2)[39m
  ] [90m(10:1)[39m
  Array [
      Identifier: a [90m(11:2)[39m
  ] [90m(11:1)[39m
  Array [
      Identifier: a [90m(12:2)[39m
      Array [
          Identifier: x [90m(12:4)[39m
      ] [90m(12:3)[39m
      Identifier: a [90m(12:6)[39m
  ] [90m(12:1)[39m
  Array [
      Identifier: c [90m(13:2)[39m
      Array [
          Identifier: s [90m(13:4)[39m
      ] [90m(13:3)[39m
      Identifier: a [90m(13:6)[39m
  ] [90m(13:1)[39m
  Array [
      Identifier: c [90m(14:2)[39m
      Array [] [90m(14:3)[39m
      Identifier: s [90m(14:5)[39m
  ] [90m(14:1)[39m
  Array [
      Array [
          Identifier: c [90m(15:3)[39m
      ] [90m(15:2)[39m
      Identifier: s [90m(15:5)[39m
  ] [90m(15:1)[39m
  Identifier: a [90m(16:1)[39m
  Array [
      Array [
          Identifier: s [90m(16:3)[39m
          Array [] [90m(16:5)[39m
          Identifier: c [90m(16:7)[39m
      ] [90m(16:4)[39m
  ] [90m(16:2)[39m
  Array [
      Array [
          Identifier: d [90m(17:3)[39m
          Array [
              Identifier: d [90m(17:5)[39m
          ] [90m(17:4)[39m
          Identifier: q [90m(17:7)[39m
      ] [90m(17:2)[39m
  ] [90m(17:1)[39m
  Array [
      Array [
          Identifier: f [90m(18:3)[39m
      ] [90m(18:2)[39m
      Array [
          Identifier: f [90m(18:6)[39m
      ] [90m(18:5)[39m
  ] [90m(18:1)[39m
  Array [
      Identifier: a [90m(19:2)[39m
      Array [] [90m(19:3)[39m
      Identifier: s [90m(19:5)[39m
      Array [
          Identifier: a [90m(19:7)[39m
          Array [] [90m(19:8)[39m
      ] [90m(19:6)[39m
      Identifier: a [90m(19:11)[39m
  ] [90m(19:1)[39m
  Identifier: a [90m(20:1)[39m
  Array [
      Array [
          Array [] [90m(20:4)[39m
      ] [90m(20:3)[39m
  ] [90m(20:2)[39m
