FILE:	/Users/nick/projects/infrared/tests/lexer/closures/closures.js
TOKENS:
  Expression () [90m(1:1)[39m
  Block {} [90m(2:1)[39m
  Array [] [90m(3:1)[39m
  Expression (
      Expression () [90m(4:2)[39m
  ) [90m(4:1)[39m
  Expression (
      Array [] [90m(5:2)[39m
  ) [90m(5:1)[39m
  Array [
      Expression () [90m(6:2)[39m
  ] [90m(6:1)[39m
  Block {
      Array [] [90m(7:2)[39m
  } [90m(7:1)[39m
  Expression (
      Expression (
          Expression () [90m(8:3)[39m
      ) [90m(8:2)[39m
  ) [90m(8:1)[39m
  Expression (
      Array [
          Block {} [90m(9:3)[39m
      ] [90m(9:2)[39m
  ) [90m(9:1)[39m
  Expression (
      Block {} [90m(10:4)[39m
      Array [] [90m(10:2)[39m
  ) [90m(10:1)[39m
  Expression (
      Expression (
          Array [] [90m(11:5)[39m
          Expression () [90m(11:2)[39m
      ) [90m(11:4)[39m
  ) [90m(11:1)[39m
  Expression (
      Identifier: a [90m(13:2)[39m
  ) [90m(13:1)[39m
  Block {
      Identifier: a [90m(14:2)[39m
  } [90m(14:1)[39m
  Array [
      Identifier: a [90m(15:2)[39m
  ] [90m(15:1)[39m
  Expression (
      Identifier: a [90m(16:6)[39m
      Expression (
          Identifier: x [90m(16:4)[39m
      ) [90m(16:3)[39m
      Identifier: a [90m(16:2)[39m
  ) [90m(16:1)[39m
  Expression (
      Identifier: a [90m(17:6)[39m
      Array [
          Identifier: s [90m(17:4)[39m
      ] [90m(17:3)[39m
      Identifier: c [90m(17:2)[39m
  ) [90m(17:1)[39m
  Array [
      Identifier: s [90m(18:5)[39m
      Expression () [90m(18:3)[39m
      Identifier: c [90m(18:2)[39m
  ] [90m(18:1)[39m
  Block {
      Identifier: s [90m(19:5)[39m
      Array [
          Identifier: c [90m(19:3)[39m
      ] [90m(19:2)[39m
  } [90m(19:1)[39m
  Identifier: a [90m(20:1)[39m
  Expression (
      Expression (
          Identifier: c [90m(20:7)[39m
          Expression () [90m(20:5)[39m
          Identifier: s [90m(20:3)[39m
      ) [90m(20:4)[39m
  ) [90m(20:2)[39m
  Expression (
      Array [
          Identifier: q [90m(21:7)[39m
          Block {
              Identifier: d [90m(21:5)[39m
          } [90m(21:4)[39m
          Identifier: d [90m(21:3)[39m
      ] [90m(21:2)[39m
  ) [90m(21:1)[39m
  Expression (
      Block {
          Identifier: f [90m(22:6)[39m
      } [90m(22:5)[39m
      Array [
          Identifier: f [90m(22:3)[39m
      ] [90m(22:2)[39m
  ) [90m(22:1)[39m
  Expression (
      Identifier: a [90m(23:11)[39m
      Expression (
          Array [] [90m(23:8)[39m
          Identifier: a [90m(23:7)[39m
      ) [90m(23:6)[39m
      Identifier: s [90m(23:5)[39m
      Expression () [90m(23:3)[39m
      Identifier: a [90m(23:2)[39m
  ) [90m(23:1)[39m
  Identifier: a [90m(24:1)[39m
  Block {
      Block {
          Block {} [90m(24:4)[39m
      } [90m(24:3)[39m
  } [90m(24:2)[39m
