{
    "Module": {
        "directives": [
            {
                "Directive": {
                    "rawValue": "use strict"
                }
            }
        ],
        "items": [
            {
                "VariableDeclarationStatement": {
                    "declaration": {
                        "VariableDeclaration": {
                            "declarators": [
                                {
                                    "VariableDeclarator": {
                                        "binding": {
                                            "VariableDeclarator": {
                                                "name": "foo"
                                            }
                                        },
                                        "init": [
                                            null
                                        ]
                                    }
                                },
                                {
                                    "VariableDeclarator": {
                                        "binding": {
                                            "VariableDeclarator": {
                                                "name": "bar"
                                            }
                                        },
                                        "init": [
                                            null
                                        ]
                                    }
                                },
                                {
                                    "VariableDeclarator": {
                                        "binding": {
                                            "VariableDeclarator": {
                                                "name": "baz"
                                            }
                                        },
                                        "init": [
                                            {
                                                "BinaryExpression": {
                                                    "left": {
                                                        "LiteralNumericExpression": {
                                                            "value": 3.0
                                                        }
                                                    },
                                                    "operator": "Plus",
                                                    "right": {
                                                        "LiteralNumericExpression": {
                                                            "value": 4.0
                                                        }
                                                    }
                                                }
                                            }
                                        ]
                                    }
                                }
                            ],
                            "kind": "Const"
                        }
                    }
                }
            }
        ]
    }
}
