{
    "Module": {
        "directives": [
            {
                "Directive": {
                    "rawValue": "use strict"
                }
            }
        ],
        "items": [
            {
                "VariableDeclarationStatement": {
                    "declaration": {
                        "VariableDeclaration": {
                            "kind": "Var",
                            "declarators": [
                                {
                                    "VariableDeclarator": {
                                        "binding": {
                                            "VariableDeclarator": {
                                                "name": "foo"
                                            }
                                        },
                                        "init": [
                                            null
                                        ]
                                    }
                                },
                                {
                                    "VariableDeclarator": {
                                        "binding": {
                                            "VariableDeclarator": {
                                                "name": "bar"
                                            }
                                        },
                                        "init": [
                                            {
                                                "BinaryExpression": {
                                                    "left": {
                                                        "LiteralNumericExpression": {
                                                            "value": 1
                                                        }
                                                    },
                                                    "operator": "Mult",
                                                    "right": {
                                                        "BinaryExpression": {
                                                            "left": {
                                                                "IdentifierExpression": {
                                                                    "name": "i"
                                                                }
                                                            },
                                                            "operator": "Plus",
                                                            "right": {
                                                                "LiteralNumericExpression": {
                                                                    "value": 3
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]
    }
}